Reason: Fix the data file location in all the source code files.         The location referred in the code is in the original Author's         computer. Now I am referring to the data folder where all the         files are present.
Problem Experienced:
(py38) ~/code/python-econometrics/src/chapter-03-simple-linear-regression$ python Simple_linear_regression.py
Traceback (most recent call last):
  File "Simple_linear_regression.py", line 11, in <module>
    data = pd.read_excel(abspath + 'SandPhedge.xls', index_col=0)
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1652, in __init__
    ext = inspect_excel_format(
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1525, in inspect_excel_format
    with get_handle(
  File "/Users/alokswain/Code/envs/py38/lib/python3.8/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/tao24/OneDrive - University of Reading/PhD/QMF Book/book Ran/data files new/Book4e_data/SandPhedge.xls'

Files modified:
   src/chapter-02-data-management/UKHP.py
   src/chapter-03-simple-linear-regression/Simple_linear_regression.py
   src/chapter-04-hedging-revisited/hedging_revisited.py
   src/chapter-05-the-CAPM/CAPM.py
   src/chapter-06-multiple-hypothesis-tests/multi-hypothesis_CAPM.py
   src/chapter-07-the-APT-and-step-wise-regression/APT.py
   src/chapter-07-the-APT-and-step-wise-regression/step-wise_reg.py.py
   src/chapter-08-quantile-regression/CAPM_quantreg.py.py
   src/chapter-09-the-PCA/PCA.py
   src/chapter-10-diagnostic-tests/autocorrelation.py.py
   src/chapter-10-diagnostic-tests/chow_test.py.py
   src/chapter-10-diagnostic-tests/dummy_variable.py.py
   src/chapter-10-diagnostic-tests/heteroscedasticity_testing.py.py
   src/chapter-10-diagnostic-tests/multicollinearity.py.py
   src/chapter-10-diagnostic-tests/newey-west_standard_error.py.py
   src/chapter-10-diagnostic-tests/non-normality.py.py
   src/chapter-10-diagnostic-tests/reset_ramsey.py.py
   src/chapter-10-diagnostic-tests/white_modifed_standard_error.py.py
   src/chapter-11-ARMA/ARMA.py.py
   src/chapter-12-ARMA-forecasting/ARMA_forecast.py.py
   src/chapter-13-exponential-smoothing-model/ARMA_exponential_smoothing.py.py
   src/chapter-14-simultaneous-equations-modelling/sme.py.py
   src/chapter-15-the-GMM/GMM.py
   src/chapter-16-VAR-estimation/VAR_IRFs.py.py
   src/chapter-17-testing-for-unit-roots/unit_root.py.py
   src/chapter-18-cointegration-tests/cointegration.py.py
   src/chapter-19-volatility-modelling/ARCH.py.py
   src/chapter-19-volatility-modelling/GARCH.py.py
   src/chapter-19-volatility-modelling/GARCH_forecast.py.py
   src/chapter-20-modelling-seasonality/Markov_switching.py.py
   src/chapter-20-modelling-seasonality/Modelling_Seasonality.py.py
   src/chapter-21-panel-data/panelex.py.py
   src/chapter-22-limited-dependent-variable/limited_dep.py.py
   src/chapter-23-simulation-methods/VaR_estimation_bootstrapping.py
   src/chapter-24-Fama-MacBeth/Fama_macbeth.py.py
   src/chapter-25-VaR-calculation/VaR_calculation.py