Reason: The old keyword 'olsresidual' has been changed to a new keyword.         Calling the function 'sms.breaks_cusumolsresid' without the         keyword argument.
        In the latest version 0.13.5 the argument is called 'resid'
        https://www.statsmodels.org/v0.13.5/generated/statsmodels.stats.diagnostic.breaks_cusumolsresid.html

        Previously it was called 'olsresidual'
        https://www.statsmodels.org/v0.10.1/generated/statsmodels.stats.diagnostic.breaks_cusumolsresid.html

Problem:
(py38) ~/code/python-econometrics/src/chapter-10-diagnostic-tests$ python chow_test.py.py
Traceback (most recent call last):
  File "chow_test.py.py", line 72, in <module>
    test = sms.breaks_cusumolsresid(olsresidual = results.resid,                                ddof = results.df_model)
TypeError: breaks_cusumolsresid() got an unexpected keyword argument 'olsresidual'

Files Changed:
   src/chapter-10-diagnostic-tests/chow_test.py.py